spring.application.name=queueless-backend

# H2 console enabled
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JDBC URL, username, password
spring.datasource.url=jdbc:h2:mem:queuelessdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Erg
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
